### PR TITLE
Level up

### PR DESCRIPTION
**Pull request by OleksandrKucherenko**
Significant improve in SDK deployment. 
Everything is prepared for jCenter/BinTray automatic repository publishing .
Used latest android tools - v25.0.0

### CODE REVIEW

**Comment by Emill** [comment]
Oh interesting!
I'll take a look at it in two weeks since I'll be away on holiday the next week.

**Comment by OleksandrKucherenko** [comment]
Now it's done!  ready for merge.

**Comment by Emill** [comment]
If we would like to publish it on bintray we would rather want to have it under our account than yours. But they only have predefined open source licenses and we need to have our own (see LICENSE.md). Apache 2.0 as you have specified at https://bintray.com/kucherenko-alex/android/io.flic%3Asdk/1.0.1.24 is wrong.

**Comment by OleksandrKucherenko** [comment]
of course. I simply show you that it works on bintray. change the API token, define own repository and publish there. I will drop my copy after that.

**Comment by Emill** [comment]
The problem is I couldn't find in bintray how to choose a custom license. I
could only choose between some predefined...

Den 23 nov. 2016 8:08 em skrev "Oleksandr" notifications@github.com:

**Pull request closed without merging**
