### PR TITLE
version up: latest gradle, latest android sdk

### PR DESCRIPTION
**Pull request by OleksandrKucherenko**
refresh the build tools of the project, so it will be possible to use it in primary projects

### CODE REVIEW

**Comment by Emill** [comment]
Nice!
I'll check it out tomorrow.

**Comment by OleksandrKucherenko** [comment]
More is comming... I did not finish it yet... Maybe today i will be able to pull second part of updates

**Comment by Emill** [comment]
Ok, nice!

Den 25 okt. 2016 8:34 fm skrev "Oleksandr" notifications@github.com:

**Comment by OleksandrKucherenko** [comment]
branch is ready for merge!

**Comment by Haves1001** [comment]
@Emill is there a reason why this isn't merged?

**Pull request closed without merging**
